import Layout from '../components/Layout';
import '../styles/globals.css';
import Head from 'next/head';
function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>todo list</title>
				<meta name="viewport" content="width=device-width, initial-scale=1" />

				<meta name="description" content="Generated by create next app" />
				<link
					rel="shortcut icon"
					href="https://images.emojiterra.com/twitter/v13.1/128px/270d.png"
					type="image/x-icon"
				/>
			</Head>
			<Layout>
				<Component {...pageProps} />
			</Layout>
		</>
	);
}

export default MyApp;
